# Generated by Django 2.2.10 on 2020-05-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletype',
            old_name='price',
            new_name='toll_fee',
        ),
    ]
