# Generated by Django 2.2.10 on 2020-05-21 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20200513_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
