# Generated by Django 2.2.12 on 2020-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20200521_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='qr_code',
            field=models.URLField(null=True),
        ),
    ]
