# Generated by Django 2.2.12 on 2020-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20200528_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
