# Generated by Django 2.2.10 on 2020-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolllocation',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
