# Generated by Django 2.2.10 on 2020-05-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20200513_1640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolls', '0003_tolllocation_collectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID'), ('PENDING', 'PENDING')], default='UNPAID', max_length=10)),
                ('paid_on', models.DateTimeField(null=True)),
                ('reference', models.CharField(max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_tolls', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tolls', to='vehicles.Vehicle')),
            ],
        ),
    ]
