# Generated by Django 2.2.12 on 2020-06-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0004_toll'),
    ]

    operations = [
        migrations.AddField(
            model_name='toll',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toll_locations', to='tolls.TollLocation'),
        ),
    ]
