# Generated by Django 2.2.12 on 2020-06-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0005_toll_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0003_auto_20200514_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toll_collectors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='toll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toll_transactions', to='tolls.Toll'),
        ),
    ]
